FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod .
RUN go mod download
COPY . .
RUN go build -o /bin/producer ./cmd/producer

FROM alpine:3.20
COPY --from=builder /bin/producer /producer
EXPOSE 8080
CMD ["/producer"]
