services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  order-service:
    build:
      context: .
      dockerfile: Dockerfile.producer
    environment:
      RABBITMQ_HTTP_URL: http://rabbitmq:15672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
    depends_on:
      - rabbitmq
    ports:
      - "8080:8080"

  payment-service:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    environment:
      RABBITMQ_HTTP_URL: http://rabbitmq:15672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
    depends_on:
      - rabbitmq
